### ISSUE TITLE
ant-design-pro的在线预览页面挂了

### ISSUE THREAD

**Issue by FVampire** [makajs/maka#2]
## What happens?

ant-design-pro的在线预览页面挂了

**Comment by ziaochina** [comment]
请用这个地址访问试试：https://makajs.github.io/maka/maka-antd-pro

**Comment by FVampire** [comment]
> 请用这个地址访问试试：https://makajs.github.io/maka/maka-antd-pro

好吧，是渲染得有点慢，不过移动端得支持还不错
